---
title: "How to use the anura dataset?"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to use the anura dataset?}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Load package and data
```{r setup, eval=F}
library(anura)
anura.data # A data.frame with anura data
anura.tree # the phylogentic tree matching species in `anura.data`
```

## Data overview
```{r}
library(anura)
knitr::kable(head(anura.data))
```

## Phylogenetic tree overview
```{r}
library(anura)
ape::plot.phylo(anura.tree, show.tip.label = FALSE, type = "f")
```

## Citation

If you use this data in publications, please cite:

Röhr, D. L., G. B. Paterno, F. Camurugi, F. A. Juncá, and A. A. Garda. 2016.
Background noise as a selective pressure: stream-breeding anurans call at higher frequencies. [Organisms Diversity and Evolution   16:269–273](https://link.springer.com/article/10.1007%2Fs13127-015-0256-0).
